language: shell
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all

addons:
  apt:
    sources:
      - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
      - shellcheck
      - jq

matrix:
  include:
    - env:
        - TESTENV=shellcheck
        - TESTCOMMAND="find $TRAVIS_BUILD_DIR -name '*.sh' -type f -print0 | xargs -0 -n1 -t shellcheck"
        - SHELLCHECK_OPTS="-s bash"
    - env:
        - TESTENV=jq
        - TESTCOMMAND="find $TRAVIS_BUILD_DIR -name '*.json' -type f -print0 | xargs -0 -n1 -I {} -t jq --exit-status . {} > /dev/null"

before_install:
  - echo $TESTCOMMAND
  - shellcheck --version
  - jq --version

install: true

script:
  - bash -c "$TESTCOMMAND"

notifications:
  email:
    on_success: never
    on_failure: always
